package com.qkd.dao;

import com.qkd.entity.DicGname;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository("DicGnameMapper")
public interface DicGnameMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic_gname
     *
     * @mbggenerated
     */
    boolean deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic_gname
     *
     * @mbggenerated
     */
    boolean saveNewDicGname(DicGname record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic_gname
     *
     * @mbggenerated
     */
    int insertSelective(DicGname record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic_gname
     *
     * @mbggenerated
     */
    DicGname selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic_gname
     *
     * @mbggenerated
     */
    boolean updateByPrimaryKeySelective(DicGname record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic_gname
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DicGname record);

    List<DicGname> listAll(DicGname dicGname);

    List<DicGname> getOneGname(String name);
}