package com.qkd.dao;

import com.qkd.entity.DicMed;
import org.springframework.stereotype.Service;

import java.util.List;

@Service("DicMedMapper")
public interface DicMedMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic_med
     *
     * @mbggenerated
     */
    boolean deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic_med
     *
     * @mbggenerated
     */
    boolean saveNewDicMed(DicMed record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic_med
     *
     * @mbggenerated
     */
    int insertSelective(DicMed record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic_med
     *
     * @mbggenerated
     */
    DicMed selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic_med
     *
     * @mbggenerated
     */
    boolean updateByPrimaryKeySelective(DicMed record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic_med
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DicMed record);


    List<DicMed> listAll(DicMed dicMed);
}