package com.qkd.dao;

import com.qkd.entity.DicPhar;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository("DicPharMapper")
public interface DicPharMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic_phar
     *
     * @mbggenerated
     */
    boolean deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic_phar
     *
     * @mbggenerated
     */
    boolean saveNewDicPhar(DicPhar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic_phar
     *
     * @mbggenerated
     */
    int insertSelective(DicPhar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic_phar
     *
     * @mbggenerated
     */
    DicPhar selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic_phar
     *
     * @mbggenerated
     */
    boolean updateByPrimaryKeySelective(DicPhar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dic_phar
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DicPhar record);


    List<DicPhar> listAll(DicPhar dicPhar);
}