package com.qkd.dao;

import com.qkd.entity.PharmacyMed;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository("PharmacyMedMapper")
public interface PharmacyMedMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pharmacy_med
     *
     * @mbggenerated
     */
    boolean deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pharmacy_med
     *
     * @mbggenerated
     */
    boolean saveNewPharmacyMed(PharmacyMed record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pharmacy_med
     *
     * @mbggenerated
     */
    int insertSelective(PharmacyMed record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pharmacy_med
     *
     * @mbggenerated
     */
    PharmacyMed selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pharmacy_med
     *
     * @mbggenerated
     */
    boolean updateByPrimaryKeySelective(PharmacyMed record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pharmacy_med
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PharmacyMed record);

    List<PharmacyMed> listAll(PharmacyMed pharmacyMed);

    boolean  updateStockByNmaeAndDepart(PharmacyMed pharmacyMed);

    boolean  reduceStockByNmaeAndDepart(PharmacyMed pharmacyMed);

    List<PharmacyMed> listAllHaveStock (PharmacyMed pharmacyMed);

}