package com.qkd.dao;

import com.qkd.entity.Position;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository("PositionMapper")
public interface PositionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier
     *
     * @mbggenerated
     */
    boolean deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier
     *
     * @mbggenerated
     */
    boolean saveNewPosition(Position position);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supplier
     *
     * @mbggenerated
     */
    boolean updateByPrimaryKeySelective(Position position);


    List<Position> listAll(Position position);
}