package com.qkd.dao;

import com.qkd.entity.Prescription;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository("PrescriptionMapper")
public interface PrescriptionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prescription
     *
     * @mbggenerated
     */
    boolean deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prescription
     *
     * @mbggenerated
     */
    boolean saveNewPrescription(Prescription record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prescription
     *
     * @mbggenerated
     */
    int insertSelective(Prescription record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prescription
     *
     * @mbggenerated
     */
    Prescription selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prescription
     *
     * @mbggenerated
     */
    boolean updateByPrimaryKeySelective(Prescription record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table prescription
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Prescription record);

    List<Prescription> listAll(Prescription prescription);

    boolean updateStatusBySerno(Prescription prescription);
}