package com.qkd.entity;

import java.io.Serializable;

public class Apply implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply.DEPART_ID
     *
     * @mbggenerated
     */
    private String departId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply.TYPE_ID
     *
     * @mbggenerated
     */
    private String typeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply.MED_ID
     *
     * @mbggenerated
     */
    private String medId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply.AMOUNT
     *
     * @mbggenerated
     */
    private Long amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply.USER_ID
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column apply.STATUS
     *
     * @mbggenerated
     */
    private String status;

    private String serno;

    private String applyDate;


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply.ID
     *
     * @return the value of apply.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply.ID
     *
     * @param id the value for apply.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply.DEPART_ID
     *
     * @return the value of apply.DEPART_ID
     *
     * @mbggenerated
     */
    public String getDepartId() {
        return departId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply.DEPART_ID
     *
     * @param departId the value for apply.DEPART_ID
     *
     * @mbggenerated
     */
    public void setDepartId(String departId) {
        this.departId = departId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply.TYPE_ID
     *
     * @return the value of apply.TYPE_ID
     *
     * @mbggenerated
     */
    public String getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply.TYPE_ID
     *
     * @param typeId the value for apply.TYPE_ID
     *
     * @mbggenerated
     */
    public void setTypeId(String typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply.MED_ID
     *
     * @return the value of apply.MED_ID
     *
     * @mbggenerated
     */
    public String getMedId() {
        return medId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply.MED_ID
     *
     * @param medId the value for apply.MED_ID
     *
     * @mbggenerated
     */
    public void setMedId(String medId) {
        this.medId = medId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply.AMOUNT
     *
     * @return the value of apply.AMOUNT
     *
     * @mbggenerated
     */
    public Long getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply.AMOUNT
     *
     * @param amount the value for apply.AMOUNT
     *
     * @mbggenerated
     */
    public void setAmount(Long amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply.USER_ID
     *
     * @return the value of apply.USER_ID
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply.USER_ID
     *
     * @param userId the value for apply.USER_ID
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column apply.STATUS
     *
     * @return the value of apply.STATUS
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column apply.STATUS
     *
     * @param status the value for apply.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status;
    }

    public String getSerno() {
        return serno;
    }

    public void setSerno(String serno) {
        this.serno = serno;
    }

    public String getApplyDate() {
        return applyDate;
    }

    public void setApplyDate(String applyDate) {
        this.applyDate = applyDate;
    }

    @Override
    public String toString() {
        return "Apply{" +
                "id=" + id +
                ", departId='" + departId + '\'' +
                ", typeId='" + typeId + '\'' +
                ", medId='" + medId + '\'' +
                ", amount=" + amount +
                ", userId='" + userId + '\'' +
                ", status='" + status + '\'' +
                ", serno='" + serno + '\'' +
                ", applyDate='" + applyDate + '\'' +
                '}';
    }
}