package com.qkd.entity;

import java.io.Serializable;

public class DicGname implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_gname.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_gname.NAME
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_gname.CODE
     *
     * @mbggenerated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_gname.ENAME
     *
     * @mbggenerated
     */
    private String ename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_gname.PHAR_ID
     *
     * @mbggenerated
     */
    private String pharId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_gname.TYPE_ID
     *
     * @mbggenerated
     */
    private String typeId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_gname.ID
     *
     * @return the value of dic_gname.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_gname.ID
     *
     * @param id the value for dic_gname.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_gname.NAME
     *
     * @return the value of dic_gname.NAME
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_gname.NAME
     *
     * @param name the value for dic_gname.NAME
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_gname.CODE
     *
     * @return the value of dic_gname.CODE
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_gname.CODE
     *
     * @param code the value for dic_gname.CODE
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_gname.ENAME
     *
     * @return the value of dic_gname.ENAME
     *
     * @mbggenerated
     */
    public String getEname() {
        return ename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_gname.ENAME
     *
     * @param ename the value for dic_gname.ENAME
     *
     * @mbggenerated
     */
    public void setEname(String ename) {
        this.ename = ename == null ? null : ename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_gname.PHAR_ID
     *
     * @return the value of dic_gname.PHAR_ID
     *
     * @mbggenerated
     */
    public String getPharId() {
        return pharId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_gname.PHAR_ID
     *
     * @param pharId the value for dic_gname.PHAR_ID
     *
     * @mbggenerated
     */
    public void setPharId(String pharId) {
        this.pharId = pharId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_gname.TYPE_ID
     *
     * @return the value of dic_gname.TYPE_ID
     *
     * @mbggenerated
     */
    public String getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_gname.TYPE_ID
     *
     * @param typeId the value for dic_gname.TYPE_ID
     *
     * @mbggenerated
     */
    public void setTypeId(String typeId) {
        this.typeId = typeId;
    }

    @Override
    public String toString() {
        return "DicGname{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", code='" + code + '\'' +
                ", ename='" + ename + '\'' +
                ", pharId=" + pharId +
                ", typeId=" + typeId +
                '}';
    }
}