package com.qkd.entity;

import java.math.BigDecimal;
import java.io.Serializable;

public class DicMed implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_med.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_med.NMAE
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_med.CODE
     *
     * @mbggenerated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_med.GNAME_ID
     *
     * @mbggenerated
     */
    private String gnameId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_med.PHAR_ID
     *
     * @mbggenerated
     */
    private String pharId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_med.TYPE_ID
     *
     * @mbggenerated
     */
    private String typeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_med.SUPPLIER_ID
     *
     * @mbggenerated
     */
    private String supplierId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_med.ORIGIN
     *
     * @mbggenerated
     */
    private String origin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_med.EFID
     *
     * @mbggenerated
     */
    private String efid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_med.TRADE_PRICE
     *
     * @mbggenerated
     */
    private BigDecimal tradePrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_med.RETAIL_PRICE
     *
     * @mbggenerated
     */
    private BigDecimal retailPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_med.PACK_UNIT
     *
     * @mbggenerated
     */
    private String packUnit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_med.PACK_NUM
     *
     * @mbggenerated
     */
    private Long packNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_med.IN_USED
     *
     * @mbggenerated
     */
    private String wmUsed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_med.OUT_USED
     *
     * @mbggenerated
     */
    private String cmUsed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dic_med.REMARK
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_med.ID
     *
     * @return the value of dic_med.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_med.ID
     *
     * @param id the value for dic_med.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_med.NMAE
     *
     * @return the value of dic_med.NMAE
     *
     * @mbggenerated
     */
    public String getNAME() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_med.NMAE
     *
     * @param name the value for dic_med.NMAE
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_med.CODE
     *
     * @return the value of dic_med.CODE
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_med.CODE
     *
     * @param code the value for dic_med.CODE
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_med.GNAME_ID
     *
     * @return the value of dic_med.GNAME_ID
     *
     * @mbggenerated
     */
    public String getGnameId() {
        return gnameId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_med.GNAME_ID
     *
     * @param gnameId the value for dic_med.GNAME_ID
     *
     * @mbggenerated
     */
    public void setGnameId(String gnameId) {
        this.gnameId = gnameId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_med.PHAR_ID
     *
     * @return the value of dic_med.PHAR_ID
     *
     * @mbggenerated
     */
    public String getPharId() {
        return pharId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_med.PHAR_ID
     *
     * @param pharId the value for dic_med.PHAR_ID
     *
     * @mbggenerated
     */
    public void setPharId(String pharId) {
        this.pharId = pharId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_med.TYPE_ID
     *
     * @return the value of dic_med.TYPE_ID
     *
     * @mbggenerated
     */
    public String getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_med.TYPE_ID
     *
     * @param typeId the value for dic_med.TYPE_ID
     *
     * @mbggenerated
     */
    public void setTypeId(String typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_med.SUPPLIER_ID
     *
     * @return the value of dic_med.SUPPLIER_ID
     *
     * @mbggenerated
     */
    public String getSupplierId() {
        return supplierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_med.SUPPLIER_ID
     *
     * @param supplierId the value for dic_med.SUPPLIER_ID
     *
     * @mbggenerated
     */
    public void setSupplierId(String supplierId) {
        this.supplierId = supplierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_med.ORIGIN
     *
     * @return the value of dic_med.ORIGIN
     *
     * @mbggenerated
     */
    public String getOrigin() {
        return origin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_med.ORIGIN
     *
     * @param origin the value for dic_med.ORIGIN
     *
     * @mbggenerated
     */
    public void setOrigin(String origin) {
        this.origin = origin == null ? null : origin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_med.EFID
     *
     * @return the value of dic_med.EFID
     *
     * @mbggenerated
     */
    public String getEfid() {
        return efid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_med.EFID
     *
     * @param efid the value for dic_med.EFID
     *
     * @mbggenerated
     */
    public void setEfid(String efid) {
        this.efid = efid == null ? null : efid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_med.TRADE_PRICE
     *
     * @return the value of dic_med.TRADE_PRICE
     *
     * @mbggenerated
     */
    public BigDecimal getTradePrice() {
        return tradePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_med.TRADE_PRICE
     *
     * @param tradePrice the value for dic_med.TRADE_PRICE
     *
     * @mbggenerated
     */
    public void setTradePrice(BigDecimal tradePrice) {
        this.tradePrice = tradePrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_med.RETAIL_PRICE
     *
     * @return the value of dic_med.RETAIL_PRICE
     *
     * @mbggenerated
     */
    public BigDecimal getRetailPrice() {
        return retailPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_med.RETAIL_PRICE
     *
     * @param retailPrice the value for dic_med.RETAIL_PRICE
     *
     * @mbggenerated
     */
    public void setRetailPrice(BigDecimal retailPrice) {
        this.retailPrice = retailPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_med.PACK_UNIT
     *
     * @return the value of dic_med.PACK_UNIT
     *
     * @mbggenerated
     */
    public String getPackUnit() {
        return packUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_med.PACK_UNIT
     *
     * @param packUnit the value for dic_med.PACK_UNIT
     *
     * @mbggenerated
     */
    public void setPackUnit(String packUnit) {
        this.packUnit = packUnit == null ? null : packUnit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_med.PACK_NUM
     *
     * @return the value of dic_med.PACK_NUM
     *
     * @mbggenerated
     */
    public Long getPackNum() {
        return packNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_med.PACK_NUM
     *
     * @param packNum the value for dic_med.PACK_NUM
     *
     * @mbggenerated
     */
    public void setPackNum(Long packNum) {
        this.packNum = packNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_med.IN_USED
     *
     * @return the value of dic_med.IN_USED
     *
     * @mbggenerated
     */
    public String getwmUsed() {
        return wmUsed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_med.IN_USED
     *
     * @param wmUsed the value for dic_med.IN_USED
     *
     * @mbggenerated
     */
    public void setwmUsed(String wmUsed) {
        this.wmUsed = wmUsed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_med.OUT_USED
     *
     * @return the value of dic_med.OUT_USED
     *
     * @mbggenerated
     */
    public String getcmUsed() {
        return cmUsed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_med.OUT_USED
     *
     * @param cmUsed the value for dic_med.OUT_USED
     *
     * @mbggenerated
     */
    public void setcmUsed(String cmUsed) {
        this.cmUsed = cmUsed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dic_med.REMARK
     *
     * @return the value of dic_med.REMARK
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dic_med.REMARK
     *
     * @param remark the value for dic_med.REMARK
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    @Override
    public String toString() {
        return "DicMed{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", code='" + code + '\'' +
                ", gnameId=" + gnameId +
                ", pharId=" + pharId +
                ", typeId=" + typeId +
                ", supplierId=" + supplierId +
                ", origin='" + origin + '\'' +
                ", efid='" + efid + '\'' +
                ", tradePrice=" + tradePrice +
                ", retailPrice=" + retailPrice +
                ", packUnit='" + packUnit + '\'' +
                ", packNum=" + packNum +
                ", wmUsed=" + wmUsed +
                ", cmUsed=" + cmUsed +
                ", remark='" + remark + '\'' +
                '}';
    }
}