package com.qkd.entity;

import java.io.Serializable;

public class Prescription implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription.PATIENT
     *
     * @mbggenerated
     */
    private String patient;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription.TYPE_ID
     *
     * @mbggenerated
     */
    private String typeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription.MED_ID
     *
     * @mbggenerated
     */
    private String medId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription.AMOUNT
     *
     * @mbggenerated
     */
    private Long amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription.USER_ID
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column prescription.STATUS
     *
     * @mbggenerated
     */
    private String status;

    private String serno;

    private String applyDate;

    private String departId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription.ID
     *
     * @return the value of prescription.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription.ID
     *
     * @param id the value for prescription.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription.PATIENT
     *
     * @return the value of prescription.PATIENT
     *
     * @mbggenerated
     */
    public String getPatient() {
        return patient;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription.PATIENT
     *
     * @param patient the value for prescription.PATIENT
     *
     * @mbggenerated
     */
    public void setPatient(String patient) {
        this.patient = patient == null ? null : patient.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription.TYPE_ID
     *
     * @return the value of prescription.TYPE_ID
     *
     * @mbggenerated
     */
    public String getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription.TYPE_ID
     *
     * @param typeId the value for prescription.TYPE_ID
     *
     * @mbggenerated
     */
    public void setTypeId(String typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription.MED_ID
     *
     * @return the value of prescription.MED_ID
     *
     * @mbggenerated
     */
    public String getMedId() {
        return medId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription.MED_ID
     *
     * @param medId the value for prescription.MED_ID
     *
     * @mbggenerated
     */
    public void setMedId(String medId) {
        this.medId = medId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription.AMOUNT
     *
     * @return the value of prescription.AMOUNT
     *
     * @mbggenerated
     */
    public Long getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription.AMOUNT
     *
     * @param amount the value for prescription.AMOUNT
     *
     * @mbggenerated
     */
    public void setAmount(Long amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription.USER_ID
     *
     * @return the value of prescription.USER_ID
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription.USER_ID
     *
     * @param userId the value for prescription.USER_ID
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column prescription.STATUS
     *
     * @return the value of prescription.STATUS
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column prescription.STATUS
     *
     * @param status the value for prescription.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status;
    }

    public String getSerno() {
        return serno;
    }

    public void setSerno(String serno) {
        this.serno = serno;
    }

    public String getApplyDate() {
        return applyDate;
    }

    public void setApplyDate(String applyDate) {
        this.applyDate = applyDate;
    }

    public String getDepartId() {
        return departId;
    }

    public void setDepartId(String departId) {
        this.departId = departId;
    }

    @Override
    public String toString() {
        return "Prescription{" +
                "id=" + id +
                ", patient='" + patient + '\'' +
                ", typeId=" + typeId +
                ", medId=" + medId +
                ", amount=" + amount +
                ", userId=" + userId +
                ", status=" + status +
                ", serno='" + serno + '\'' +
                ", applyDate='" + applyDate + '\'' +
                '}';
    }
}