package com.qkd.entity;

import java.io.Serializable;
import java.util.Date;

public class Purchase implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase.DEPART_ID
     *
     * @mbggenerated
     */
    private String departId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase.SUPPILER_ID
     *
     * @mbggenerated
     */
    private String supplierId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase.TYPE_ID
     *
     * @mbggenerated
     */
    private String typeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase.MED_ID
     *
     * @mbggenerated
     */
    private String medId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase.AMOUNT
     *
     * @mbggenerated
     */
    private Long amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase.USER_ID
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column purchase.STATUS
     *
     * @mbggenerated
     */
    private String status;

    private String serno;

    private String applyDate;

    private String backReason;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase.ID
     *
     * @return the value of purchase.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase.ID
     *
     * @param id the value for purchase.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase.DEPART_ID
     *
     * @return the value of purchase.DEPART_ID
     *
     * @mbggenerated
     */
    public String getDepartId() {
        return departId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase.DEPART_ID
     *
     * @param departId the value for purchase.DEPART_ID
     *
     * @mbggenerated
     */
    public void setDepartId(String departId) {
        this.departId = departId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase.SUPPILER_ID
     *
     * @return the value of purchase.SUPPILER_ID
     *
     * @mbggenerated
     */
    public String getsupplierId() {
        return supplierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase.SUPPILER_ID
     *
     * @param supplierId the value for purchase.SUPPILER_ID
     *
     * @mbggenerated
     */
    public void setsupplierId(String supplierId) {
        this.supplierId = supplierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase.TYPE_ID
     *
     * @return the value of purchase.TYPE_ID
     *
     * @mbggenerated
     */
    public String getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase.TYPE_ID
     *
     * @param typeId the value for purchase.TYPE_ID
     *
     * @mbggenerated
     */
    public void setTypeId(String typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase.MED_ID
     *
     * @return the value of purchase.MED_ID
     *
     * @mbggenerated
     */
    public String getMedId() {
        return medId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase.MED_ID
     *
     * @param medId the value for purchase.MED_ID
     *
     * @mbggenerated
     */
    public void setMedId(String medId) {
        this.medId = medId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase.AMOUNT
     *
     * @return the value of purchase.AMOUNT
     *
     * @mbggenerated
     */
    public Long getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase.AMOUNT
     *
     * @param amount the value for purchase.AMOUNT
     *
     * @mbggenerated
     */
    public void setAmount(Long amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase.USER_ID
     *
     * @return the value of purchase.USER_ID
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase.USER_ID
     *
     * @param userId the value for purchase.USER_ID
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column purchase.STATUS
     *
     * @return the value of purchase.STATUS
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column purchase.STATUS
     *
     * @param status the value for purchase.STATUS
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status;
    }

    public String getSerno() {
        return serno;
    }

    public void setSerno(String serno) {
        this.serno = serno;
    }

    public String getApplyDate() {
        return applyDate;
    }

    public void setApplyDate(String applyDate) {
        this.applyDate = applyDate;
    }

    public String getBackReason() {
        return backReason;
    }

    public void setBackReason(String backReason) {
        this.backReason = backReason;
    }

    @Override
    public String toString() {
        return "Purchase{" +
                "id=" + id +
                ", departId='" + departId + '\'' +
                ", supplierId='" + supplierId + '\'' +
                ", typeId='" + typeId + '\'' +
                ", medId='" + medId + '\'' +
                ", amount=" + amount +
                ", userId='" + userId + '\'' +
                ", status='" + status + '\'' +
                ", serno='" + serno + '\'' +
                ", applyDate=" + applyDate +
                '}';
    }
}