package com.qkd.entity;

import java.io.Serializable;

public class User implements Serializable{

    private static final long serialVersionUID = 1L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.NAME
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.CODE
     *
     * @mbggenerated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.PWD
     *
     * @mbggenerated
     */
    private String pwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.DEPART_ID
     *
     * @mbggenerated
     */
    private String departId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.POWER_STATUS
     *
     * @mbggenerated
     */
    private String powerStatus;

    public User() {
    }

    public User(Integer id, String name, String pwd, String code, String departId, String powerStatus) {
        this.id = id;
        this.name = name;
        this.pwd = pwd;
        this.code = code;
        this.departId = departId;
        this.powerStatus = powerStatus;
    }

    public static long getSerialVersionUID() {
        return serialVersionUID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.ID
     *
     * @return the value of user.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.ID
     *
     * @param id the value for user.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.NAME
     *
     * @return the value of user.NAME
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.NAME
     *
     * @param name the value for user.NAME
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.CODE
     *
     * @return the value of user.CODE
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.CODE
     *
     * @param code the value for user.CODE
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.PWD
     *
     * @return the value of user.PWD
     *
     * @mbggenerated
     */
    public String getPwd() {
        return pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.PWD
     *
     * @param pwd the value for user.PWD
     *
     * @mbggenerated
     */
    public void setPwd(String pwd) {
        this.pwd = pwd == null ? null : pwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.DEPART_ID
     *
     * @return the value of user.DEPART_ID
     *
     * @mbggenerated
     */
    public String getDepartId() {
        return departId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.DEPART_ID
     *
     * @param departId the value for user.DEPART_ID
     *
     * @mbggenerated
     */
    public void setDepartId(String departId) {
        this.departId = departId == null ? null : departId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.POWER_STATUS
     *
     * @return the value of user.POWER_STATUS
     *
     * @mbggenerated
     */
    public String getPowerStatus() {
        return powerStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.POWER_STATUS
     *
     * @param powerStatus the value for user.POWER_STATUS
     *
     * @mbggenerated
     */
    public void setPowerStatus(String powerStatus) {
        this.powerStatus = powerStatus == null ? null : powerStatus.trim();
    }

    @Override
    public String toString() {
        return "User{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", code='" + code + '\'' +
                ", pwd='" + pwd + '\'' +
                ", departId='" + departId + '\'' +
                ", powerStatus='" + powerStatus + '\'' +
                '}';
    }
}